[package]
name = "to_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
nylisp_eval = "0.2.4"
wasm-bindgen = "0.2.78"
wasm-bindgen-test = "0.3.0"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1